version: "3"
services:
  sma_app:
    build: .
    image: elleined/sma
    container_name: sma_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sma_db
      - PORT=8081
    networks:
      - sma_network
    depends_on:
      mysql_server:
        condition: service_healthy
  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sma_db
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    networks:
      - sma_network
networks:
  sma_network:
    name: sma_network
    ipam:
      driver: default
    external: false
