version: "3"
services:
  sma_api:
    build: .
    image: elleined/sma
    container_name: sma_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=sma_mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sma_db
    networks:
      - sma_network
    depends_on:
      - sma_mysql_server
  sma_mysql_server:
    image: mysql:8.0.32
    container_name: sma_mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sma_db
    ports:
      - "3307:3306"
    networks:
      - sma_network
networks:
  sma_network:
    name: sma_network
    ipam:
      driver: default
    external: false
