version: "3.8"
services:
  social_media_api:
    image: elleined/social-media-api:latest
    container_name: social_media_api
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - sma_network
    depends_on:
      mysql_server:
        condition: service_healthy

  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 300s
    networks:
      - sma_network

networks:
  sma_network:
    name: sma_network
    ipam:
      driver: default
    external: false
